# Generated by Django 4.2 on 2023-05-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='bet',
            name='api_bet_user_id_ef2b58_idx',
        ),
        migrations.RemoveIndex(
            model_name='bet',
            name='api_bet_game_id_172b4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='bet',
            name='api_bet_amount_feba95_idx',
        ),
        migrations.RemoveIndex(
            model_name='bet',
            name='api_bet_status_b17b85_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='api_game_name_3c7117_idx',
        ),
        migrations.RemoveIndex(
            model_name='game',
            name='api_game_categor_8dd30d_idx',
        ),
        migrations.RemoveIndex(
            model_name='mediator',
            name='api_mediato_name_9bcecd_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_user_id_87976a_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_amount_b70359_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='api_transac_date_ti_3c0ca7_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='api_user_created_b958a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='api_user_updated_6e25b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='usercontact',
            name='api_usercon_user_id_ea450a_idx',
        ),
        migrations.RemoveIndex(
            model_name='usercontact',
            name='api_usercon_phone_n_0b94a5_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='mediator',
            name='mediator_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='api_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(related_name='api_users', to='auth.permission'),
        ),
    ]
